# https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system
sudo: false
dist: xenial

language: go
go:
  - "1.11"

# Only clone the most recent commit.
git:
  depth: 1

env:
  - DEP_VERSION="0.5.0"

before_install:
  # Dump environment variables
  - printenv
  # Download dep binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  - "go get -u -v honnef.co/go/tools/cmd/staticcheck"
  - "cd signallerd; dep ensure"

before_script:
  - "make signaller"

script:
  # Static Analysis (vet)
  - "make vet"

  # Check formatting
  - "make check-formatting"
